### ISSUE TITLE
The web server at http://localhost:8080/openscoring did not identify itself as Openscoring/2.0 service

### ISSUE THREAD

**Issue by hansenmaster** [openscoring/openscoring-python#12]
Hello, I am trying to do iris example by PMML in Python
![image](https://user-images.githubusercontent.com/36762228/56782032-8e237f80-680f-11e9-8a97-ac16aa633cce.png)

What I understand to run openscoring, we need the openscoring server that run on http://localhost:8080/openscoring/

But when I run, i encountered this error saying like the server doesn't provide  the right thing
![image](https://user-images.githubusercontent.com/36762228/56782122-ece8f900-680f-11e9-9342-999b4022290c.png)

When I use my browser to see http://localhost:8080/openscoring/ , I see there is no message.
![image](https://user-images.githubusercontent.com/36762228/56782150-08ec9a80-6810-11e9-9d79-7900be56f21c.png)

Could you help me figure out what is wrong? I tried to run the server from 
openscoring-server-executable-1.4.3.jar .

**Comment by vruusmann** [comment]
One must pair [Openscoring-Python](https://github.com/openscoring/openscoring-python) client with the right version of [Openscoring](https://github.com/openscoring/openscoring) server. This is so, because the client must understand the protocol/API that the server is using.

When using Openscoring 1.4.X (the latest being 1.4.5), use Openscoring-Python 0.4.X. When using Openscoring 2.0.X, use Openscoring-Python 0.5.X.

**Comment by hansenmaster** [comment]
Hello, thank you for the response.
Form my error message, does it say I need the Opensscoring 2.0.x Server to run the python code?

How do I know my Openscoring-python server?
I cannot find Openscoring 2.0.X server jar, it say the newest version is 1.4.5

**Comment by vruusmann** [comment]
> Form my error message, does it say I need the Opensscoring 2.0.x Server to run the python code?

You are using Openscoring-Python 0.5.X to connect to Openscoring 1.4.X. It's not allowed due to protocol/API changes.

> How do I know my Openscoring-python server?

What did you download and run?

> I cannot find Openscoring 2.0.X server jar, it say the newest version is 1.4.5

Openscoring 2.0.X is available in the `master` branch of the GitHub source code repository. The inaugural `2.0.0` release version hasn't been finalized and published yet, though.

**Comment by hansenmaster** [comment]
Hi thank you for the response,
https://github.com/openscoring/openscoring-python
 Using this comment 
![image](https://user-images.githubusercontent.com/36762228/56881647-490b8180-6a8b-11e9-97bb-521ff387a3c8.png)

How can I install Openscoring-Python 0.4.X?

**Comment by vruusmann** [comment]
> How can I install Openscoring-Python 0.4.X?

```
$ git clone https://github.com/openscoring/openscoring-python.git
$ cd openscoring-python
$ git checkout <TAG>
$ pip install .
```
